// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {

    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfTjFbl2m_dqqTj8unXosf3Y0daTp6uOw',
    appId: '1:235789632621:web:b9dbefab1914cc1fb1ab64',
    messagingSenderId: '235789632621',
    projectId: 'projetiot-b3aa7',
    authDomain: 'projetiot-b3aa7.firebaseapp.com',
    storageBucket: 'projetiot-b3aa7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1w9cJCVbnbVH1CSUmnYiFC0LjdHRB8qo',
    appId: '1:235789632621:android:adf834e31d64fb5bb1ab64',
    messagingSenderId: '235789632621',
    projectId: 'projetiot-b3aa7',
    storageBucket: 'projetiot-b3aa7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbtLvD-fkABAxs7TnTsw8KBCE3Q7SMFMQ',
    appId: '1:235789632621:ios:417319f6c20880e0b1ab64',
    messagingSenderId: '235789632621',
    projectId: 'projetiot-b3aa7',
    storageBucket: 'projetiot-b3aa7.firebasestorage.app',
    iosBundleId: 'com.example.projectIotMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbtLvD-fkABAxs7TnTsw8KBCE3Q7SMFMQ',
    appId: '1:235789632621:ios:417319f6c20880e0b1ab64',
    messagingSenderId: '235789632621',
    projectId: 'projetiot-b3aa7',
    storageBucket: 'projetiot-b3aa7.firebasestorage.app',
    iosBundleId: 'com.example.projectIotMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfTjFbl2m_dqqTj8unXosf3Y0daTp6uOw',
    appId: '1:235789632621:web:2acedca4b9569fffb1ab64',
    messagingSenderId: '235789632621',
    projectId: 'projetiot-b3aa7',
    authDomain: 'projetiot-b3aa7.firebaseapp.com',
    storageBucket: 'projetiot-b3aa7.firebasestorage.app',
  );


}
